### ISSUE TITLE
Make load page functional

### ISSUE THREAD

**Issue by DaniBodor** [EIT-ALIVE/eit_dash#19]
Allow for a single sample dataset to be loaded and work.

Also implement the following 'design' changes:
- [x] instead of "add dataset" popup, integrate it in the column.
- [x] Use terminology from eitprocessing library (at least for now). So instead of "dataset", call it a Sequence.

**Comment by wbaccinelli** [comment]
Changes to be implemented:
- add possibility to remove selected dataset
- possibility to rename existing dataset
- add duration of the selection in the dataset
- remove vendor field in dataset summary
- plot with different color the already selected data part
- add instructions that can be shrinked/expanded (maybe bottom left?)


Nice to have:
- change the starting and end point of existing selections
- shrink/expand columns size
