### ISSUE TITLE
Initial design of preprocessing page

### ISSUE THREAD

**Issue by DaniBodor** [EIT-ALIVE/eit_dash#9]
- [ ] Show previous step
  - Identical to results of load page? or abbreviated version?
- [ ] Resampling row
  - Choose algorithm for interpolation (include at least linear, optionally others in the future)
- [ ] Add Synchronization button
- [ ] Choose synchronization algorithm
- [ ] Select datasets / timepoints in multiple datasets
- [ ] Set sync algorithm parameters
- [ ] Show summary in results column
- [ ] ...

Mainly resampling and rough sync from manual input (based on visual info)

**Comment by wbaccinelli** [comment]
See [new version of the mockup](https://teams.microsoft.com/_#/pptx/viewer/teamsSdk/https:~2F~2Ferasmusmc.sharepoint.com~2Fsites~2FALIVEproject-eScienceCenter~2FGedeelde%20documenten~2FGeneral~2FGUI%20mockup~2FProposal%20GUI%20mockup%20-%20v2.pptx?threadId=19:lgAgpLnaQc5WtkhmgFybruvHtzF46rvlI752HOSUwyo1@thread.tacv2&subEntityId=%257B%2522viewParams%2522%253A%2522id%253D%25252Fsites%25252FALIVEproject%25252DeScienceCenter%25252FGedeelde%252520documenten%25252FGeneral%25252FGUI%252520mockup%2526listurl%253D%25252Fsites%25252FALIVEproject%25252DeScienceCenter%25252FGedeelde%252520documenten%2526viewid%253D298cfea7%25252D70eb%25252D495b%25252D93c6%25252Df4cda417031b%2522%257D&baseUrl=https:~2F~2Ferasmusmc.sharepoint.com~2Fsites~2FALIVEproject-eScienceCenter&fileId=31bc10a1-c2e9-44ea-8c9e-9a13f5cbb5e0&ctx=openFilePreview&viewerAction=edit)

**Comment by DaniBodor** [comment]
- Resample frequency set only once per Sequence.
  - Check whether it should be allowed to use different resampling frequencies between different Sequences of the same run
- If frequency changes, it should overwrite the previous setting instead of adding a new row.
- rename Dataset to Sequence
